In [274]:
import numpy as np
import pandas as pd
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'

In [275]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import confusion_matrix

In [276]:
iris = pd.read_csv("iris.csv")
iris.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [277]:
iris = iris.drop("Unnamed: 0",axis =1)
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
#creating a separate dataframe 
pred = {"pred1":np.array(np.repeat(np.nan,len(iris)),dtype ="<U10")}
pred = pd.DataFrame(data=pred)

In [78]:
pred = {"pred00":np.array(np.repeat(np.nan,len(iris)),dtype ="<U10")}
pred = pd.DataFrame(data=pred)

In [79]:
pred

pred00
0      nan
1      nan
2      nan
3      nan
4      nan
..     ...
145    nan
146    nan
147    nan
148    nan
149    nan

[150 rows x 1 columns]

In [80]:
pred["pred1"]=pred["pred00"]
pred

pred00 pred1
0      nan   nan
1      nan   nan
2      nan   nan
3      nan   nan
4      nan   nan
..     ...   ...
145    nan   nan
146    nan   nan
147    nan   nan
148    nan   nan
149    nan   nan

[150 rows x 2 columns]

In [81]:
#Bagging Round 1 
boot = iris.sample(len(iris),replace = True)

uniq_indx = np.unique(boot.index)
test_index = []
for i in range(0,len(iris)):
    if i not in uniq_indx:
        test_index.append(i)
        
(len(test_index) , len(uniq_indx))

(54, 96)

In [82]:
len(test_index)

54

In [83]:

#out-of-bag-data 
test = iris.iloc[test_index]
test.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1            4.9          3.0           1.4          0.2  setosa
6            4.6          3.4           1.4          0.3  setosa
8            4.4          2.9           1.4          0.2  setosa
10           5.4          3.7           1.5          0.2  setosa
13           4.3          3.0           1.1          0.1  setosa

In [84]:
#splitting X and Y 
X_boot = boot.drop("Species",axis =1)
Y_boot = boot["Species"]
X_test  = test.drop("Species",axis =1)
Y_test = test["Species"]

In [85]:
#Training the model on Bootstrap sample 
tree = DecisionTreeClassifier(criterion = "gini",min_samples_leaf =5)
tree.fit(X_boot,Y_boot)

DecisionTreeClassifier(min_samples_leaf=5)

In [86]:
predict = tree.predict(X_test)
predict[4]


'setosa'

In [87]:
predict

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'versicolor', 'virginica',
       'virginica', 'virginica', 'versicolor', 'versicolor', 'virginica',
       'virginica'], dtype=object)

In [89]:
#bagging the first predicted value...
j=0
for i in range(0,len(iris)-1):
    if i in test_index:
        pred["pred1"][i]=predict[j]
        j=j+1
        print(predict[j])
    
        
pred    

setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
setosa
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
virginica
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
versicolor
virginica
virginica
virginica
virginica
virginica
virginica
virginica
virginica
versicolor
virginica
virginica
virginica
versicolor
versicolor
virginica
virginica


IndexError: index 54 is out of bounds for axis 0 with size 54

In [67]:
pred["pred1"][122]

'virginica'

In [75]:
pred = pred.drop("pred149",axis =1)
pred.head()


pred0   pred1   pred2
0   nan     nan     nan
1   nan     nan  setosa
2   nan     nan     nan
3   nan  setosa     nan
4   nan  setosa  setosa

In [68]:
pred["pred1"].unique()

array(['nan', 'setosa', 'versicolor', 'virginica'], dtype=object)

In [91]:
#Bagging Round 2 
#Step 1 to get the bootstrap sample
boot = iris.sample(len(iris),replace = True)

# Step 2 get the indices for out-of-bag-data
uniq_indx = np.unique(boot.index)
test_index = []
for i in range(0,len(iris)):
    if i not in uniq_indx:
        test_index.append(i)


test = iris.iloc[test_index]
test.head()

# Step 3 splitting X and Y 
X_boot = boot.drop("Species",axis =1)
Y_boot = boot["Species"]
X_test  = test.drop("Species",axis =1)
Y_test = test["Species"]

# Step 4 Training the model on Bootstrap sample 
tree = DecisionTreeClassifier(criterion = "gini",min_samples_leaf =5)
tree.fit(X_boot,Y_boot)

# Step 5 get the predicted value on test data
predict = tree.predict(X_test)

# Step 6 add new predict column
pred["pred2"] = pred["pred00"]

# Step 6 bagging the second predicted value...
j=0
for i in range(0,len(iris)-1):
    if i in test_index:
        pred["pred2"][i]=predict[j]
        j=j+1
        
pred

pred00   pred1      pred2
0      nan     nan     setosa
1      nan  setosa     setosa
2      nan     nan        nan
3      nan     nan        nan
4      nan     nan        nan
..     ...     ...        ...
145    nan     nan  virginica
146    nan     nan  virginica
147    nan     nan        nan
148    nan     nan  virginica
149    nan     nan        nan

[150 rows x 3 columns]

In [92]:
#Bagging Round 3 
#Step 1 to get the bootstrap sample
boot = iris.sample(len(iris),replace = True)

# Step 2 get the indices for out-of-bag-data
uniq_indx = np.unique(boot.index)
test_index = []
for i in range(0,len(iris)):
    if i not in uniq_indx:
        test_index.append(i)


test = iris.iloc[test_index]
test.head()

# Step 3 splitting X and Y 
X_boot = boot.drop("Species",axis =1)
Y_boot = boot["Species"]
X_test  = test.drop("Species",axis =1)
Y_test = test["Species"]

# Step 4 Training the model on Bootstrap sample 
tree = DecisionTreeClassifier(criterion = "gini",min_samples_leaf =5)
tree.fit(X_boot,Y_boot)

# Step 5 get the predicted value on test data
predict = tree.predict(X_test)

# Step 6 add new predict column
pred["pred3"] = pred["pred00"]

# Step 6 bagging the second predicted value...
j=0
for i in range(0,len(iris)-1):
    if i in test_index:
        pred["pred3"][i]=predict[j]
        j=j+1
        
pred

pred00   pred1      pred2      pred3
0      nan     nan     setosa        nan
1      nan  setosa     setosa        nan
2      nan     nan        nan     setosa
3      nan     nan        nan     setosa
4      nan     nan        nan     setosa
..     ...     ...        ...        ...
145    nan     nan  virginica        nan
146    nan     nan  virginica  virginica
147    nan     nan        nan        nan
148    nan     nan  virginica  virginica
149    nan     nan        nan        nan

[150 rows x 4 columns]

In [286]:
pred = {"pred00":np.array(np.repeat(np.nan,len(iris)))}
pred = pd.DataFrame(data=pred)
pred

pred00
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
..      ...
145     NaN
146     NaN
147     NaN
148     NaN
149     NaN

[150 rows x 1 columns]

In [297]:
#20 rounds of bagging
pred = {"pred00":np.array(np.repeat(np.nan,len(iris)))}
pred = pd.DataFrame(data=pred)
rounds = 50
models = []
for l in range(0,rounds):
    
    #Step 1 to get the bootstrap sample
    boot = iris.sample(len(iris),replace = True)
    
    # Step 2 get the indices for out-of-bag-data
    uniq_indx = np.unique(boot.index)
    test_index = []
    for m in range(0,len(iris)):
        if m not in uniq_indx:
            test_index.append(m)


    test = iris.iloc[test_index]
    #test.head()
    # Step 3 splitting X and Y 
    X_boot = boot.drop("Species",axis =1)
    Y_boot = boot["Species"]
    X_test  = test.drop("Species",axis =1)
    Y_test = test["Species"]
    
    # Step 4 Training the model on Bootstrap sample 
    tree = DecisionTreeClassifier(criterion = "gini",min_samples_leaf =5)
    tree.fit(X_boot,Y_boot)
    models.append(tree)
    
    # Step 5 get the predicted value on test data
    predict = tree.predict(X_test)
    
    # Step 6 add new predict column
    p = "pred"+str(l)
    pred[p] = pred["pred00"]
    
    # Step 7 bagging the second predicted value...
    j=0
    for n in range(0,len(iris)):
        if n in test_index:
            pred[p][n]=predict[j]
            j=j+1
        
pred

pred00      pred0      pred1      pred2      pred3      pred4      pred5  \
0       NaN        NaN        NaN     setosa     setosa        NaN     setosa   
1       NaN        NaN        NaN        NaN        NaN        NaN        NaN   
2       NaN     setosa        NaN     setosa        NaN        NaN        NaN   
3       NaN     setosa     setosa        NaN        NaN     setosa     setosa   
4       NaN        NaN        NaN        NaN     setosa     setosa        NaN   
..      ...        ...        ...        ...        ...        ...        ...   
145     NaN        NaN        NaN        NaN        NaN  virginica  virginica   
146     NaN  virginica        NaN        NaN        NaN        NaN        NaN   
147     NaN  virginica        NaN  virginica  virginica  virginica  virginica   
148     NaN        NaN  virginica        NaN        NaN        NaN  virginica   
149     NaN        NaN  virginica        NaN        NaN        NaN        NaN   

         pred6      pred7      pred8  ...     pred40     pred41 pred42  \
0       setosa        NaN        NaN  ...        NaN        NaN    NaN   
1          NaN     setosa     setosa  ...     setosa     setosa    NaN   
2          NaN        NaN     setosa  ...        NaN     setosa    NaN   
3          NaN        NaN        NaN  ...        NaN     setosa    NaN   
4          NaN        NaN        NaN  ...        NaN     setosa    NaN   
..         ...        ...        ...  ...        ...        ...    ...   
145  virginica        NaN        NaN  ...        NaN        NaN    NaN   
146  virginica        NaN  virginica  ...  virginica  virginica    NaN   
147        NaN        NaN  virginica  ...        NaN        NaN    NaN   
148        NaN  virginica  virginica  ...  virginica  virginica    NaN   
149  virginica        NaN        NaN  ...  virginica        NaN    NaN   

        pred43     pred44     pred45     pred46     pred47     pred48  \
0       setosa        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN     setosa        NaN        NaN        NaN   
2       setosa     setosa        NaN        NaN     setosa        NaN   
3          NaN        NaN        NaN        NaN        NaN        NaN   
4          NaN        NaN        NaN        NaN        NaN     setosa   
..         ...        ...        ...        ...        ...        ...   
145        NaN        NaN        NaN        NaN  virginica        NaN   
146        NaN  virginica  virginica  virginica        NaN  virginica   
147        NaN        NaN        NaN        NaN        NaN        NaN   
148  virginica  virginica  virginica        NaN  virginica  virginica   
149        NaN        NaN  virginica  virginica        NaN  virginica   

        pred49  
0          NaN  
1          NaN  
2       setosa  
3          NaN  
4          NaN  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 51 columns]

In [299]:
predictions = []
for i in range(0,pred.shape[0]):
    
    p = []
    p = pred.iloc[i,:]
    count = p.value_counts().index.tolist()
    predictions.append(count[0])
predictions

['setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'versicolor',
 'versicolor',
 'virginica',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'versicolor',
 'versicolor',
 'v

In [300]:
cm = confusion_matrix(iris.Species,predictions)

(cm,(cm[0,0]+cm[1,1]+cm[2,2])/150)


(array([[50,  0,  0],
        [ 0, 46,  4],
        [ 0,  5, 45]], dtype=int64), 0.94)

In [229]:
predictions = []
for i in range(0,pred.shape[0]):
    
    p = []
    p = pred.iloc[i,:]
    q = [i for i in p if str(p) != 'nan']
    m=[]
    for value in range(0,len(q)):
        if q[value] != 0:
            m.append(q[value])
    
    
    #print(m)
    #q = [i for i in p if str(p) != 'nan']
    #print(statistics.mode(m))
    #v = "final"
    
    predictions.append(statistics.mode(m))

len(predictions)    

StatisticsError: no unique mode; found 2 equally common values

In [204]:
confusion_matrix(iris.Species,predictions)

array([[50,  0,  0],
       [ 0, 44,  6],
       [ 0,  2, 48]], dtype=int64)

In [205]:
acc = (50+44+48)/150
acc

0.9466666666666667

In [194]:
import statistics
p = []
p = pred.iloc[1,:]
q = [i for i in p if str(p) != 'nan']
m=[]
for value in range(0,len(q)):

    if q[value] != 0.0:
        m.append(q[value])
        
print(m)
#q = [i for i in p if str(p) != 'nan']
statistics.mode(m)
#pred.loc["final"][0]=statistics.mode(m)



['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa']


'setosa'

In [292]:
predictions = []
for i in range(0,pred.shape[0]):
    
    p = []
    p = pred.iloc[i,:]
    count = p.value_counts().index.tolist()
    predictions.append(count[0])
predictions

['nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'versicolor',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 

In [247]:
p = []
p = pred.iloc[134,:]
count = p.value_counts().index.tolist()
count[0]

'versicolor'

In [249]:
confusion_matrix(iris.Species,predictions)

array([[50,  0,  0],
       [ 0, 46,  4],
       [ 0,  5, 45]], dtype=int64)

In [251]:
acc = (50+46+45)/150
acc

0.94

In [301]:
#20 rounds of bagging
# Step 0 Creating Dataframe for bagging predictions
pred = {"pred00":np.array(np.repeat(np.nan,len(iris)),dtype ="<U10")}
pred = pd.DataFrame(data=pred)
rounds = 50
models = []
#Start the loop for 50 rounds
for l in range(0,rounds):
    
    #Step 1 to get the bootstrap sample
    boot = iris.sample(len(iris),replace = True)
    
    # Step 2 get the indices for out-of-bag-data
    uniq_indx = np.unique(boot.index)
    test_index = []
    for m in range(0,len(iris)):
        if m not in uniq_indx:
            test_index.append(m)


    test = iris.iloc[test_index]
    #test.head()
    # Step 3 splitting X and Y 
    X_boot = boot.drop("Species",axis =1)
    Y_boot = boot["Species"]
    X_test  = test.drop("Species",axis =1)
    Y_test = test["Species"]
    
    # Step 4 Training the model on Bootstrap sample 
    tree = DecisionTreeClassifier(criterion = "gini",min_samples_leaf =5)
    tree.fit(X_boot,Y_boot)
    models.append(tree)
    
    # Step 5 get the predicted value on test data
    predict = tree.predict(X_test)
    
    # Step 6 add new predict column
    p = "pred"+str(l)
    pred[p] = pred["pred00"]
    
    # Step 7 bagging the nth predicted value...
    j=0
    for n in range(0,len(iris)):
        if n in test_index:
            pred[p][n]=predict[j]
            j=j+1

#Step 8 BAGGING the Predictions:Making the Final Prediction            
predictions = []
for i in range(0,pred.shape[0]):
    
    p = []
    p = pred.iloc[i,:]
    count = p.value_counts().index.tolist()
    predictions.append(count[0])
    
pred
cm = confusion_matrix(iris.Species,predictions)
cm
#(cm,(cm[0,0]+cm[1,1]+cm[2,2])/150)

array([[ 0,  0,  0,  0],
       [50,  0,  0,  0],
       [50,  0,  0,  0],
       [48,  0,  0,  2]], dtype=int64)