## Machine Learning - Session 1 - NumPy

In [1]:
#Import the numpy library
import numpy as np

#### A. Defining a 1D numpy array

In [2]:
l = [12,34,24,45,7,18]

In [3]:
type(l)

list

In [4]:
x = np.array([12,34,24,45,7,18])
x

array([12, 34, 24, 45,  7, 18])

In [5]:
type(x)

numpy.ndarray

#### B. Creating Regular Sequence

In [7]:
#Create a regular sequence of integers starting from 1 to 10. integers = [1,2,3,4,.......,10]

integers = np.arange(1, 11, 1)
integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
#Create a regular sequence of integers starting from 10 to 1.

integers = np.arange(10, 0, -1)
integers

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [3]:
#Create a regular sequence of even integers between 10 to 20

even = np.arange(10,21,2)
even

array([10, 12, 14, 16, 18, 20])

In [4]:
#Create a regular sequence of the following type: [10.0,10.5,11.0,11.5, ... , 19.5, 20.0]

seq = np.arange(10,21,0.5)
seq


array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [8]:
#Create a regular sequence of length 20 ranging from 0 to 5

np.linspace(start = 0, stop = 5, num = 20, endpoint = True)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [ ]:
#Help for np.linspace

??np.linspace   #Shift + tab

In [5]:
import numpy as np
np.random.seed(9)
x = np.random.randint(1,100,100)
x

array([93, 55, 57, 23, 66, 23, 53, 60, 41, 92, 34, 94, 93,  1, 61, 60, 89,
       75, 57, 94, 63, 13, 19, 87, 57,  2, 57, 12, 38, 20, 10, 81, 57, 50,
       64, 14, 60, 59, 34, 78, 94, 55, 64, 23, 51, 41,  5, 53, 59,  1, 75,
       57, 17,  5,  6, 25, 20, 31, 41,  5, 73, 65,  2, 35, 92, 78, 72, 16,
       47, 67, 30, 51, 99, 62, 20, 42, 43, 51, 20, 49, 82, 97, 35, 17, 43,
       57, 15, 76, 30, 72, 92, 33, 83, 37, 92, 65,  2, 88, 34, 87])

In [5]:
#Studying the arange function

help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

#### C. Creating a Random Sequence

In [10]:
#Generate 20 random numbers between 1 and 100 (with replacements)
np.random.seed(0)
a = np.random.randint(1,100,20)
a

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89])

In [8]:
np.random.seed(0)
b=np.random.random(20)
b

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [11]:
np.random.seed(0)
a+b

array([45.5488135 , 48.71518937, 65.60276338, 68.54488318, 68.4236548 ,
       10.64589411, 84.43758721, 22.891773  , 37.96366276, 88.38344152,
       71.79172504, 89.52889492, 89.56804456, 13.92559664, 59.07103606,
       66.0871293 , 40.0202184 , 88.83261985, 47.77815675, 89.87001215])

In [ ]:
#help(np.random.randint)

In [6]:
l = [12,34,24,45,7,18]

#Shuffle the vector x
x = np.array(l)
np.random.shuffle(x)
x

array([45, 18, 34,  7, 12, 24])

In [ ]:
x

In [11]:
np.random.choice(l,2)

array([ 7, 45])

In [12]:
np.random.choice(x,15,replace=True)

array([24,  7, 34, 24, 12,  7, 24, 45,  7, 34,  7,  7, 24, 45, 45])

In [14]:
np.random.choice(x,6,replace=False)

array([24, 34, 18,  7, 45, 12])

To find more on numpy random sampling Go To this link 
https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html 

#### D. Some basic numpy methods

In [16]:
[12,34,24.0,45,7,18]

[12, 34, 24.0, 45, 7, 18]

In [29]:
x = np.array([12,34,24,45,7.0,18])

In [15]:
#Size of the array
x.size

6

In [28]:
x = np.array([12,34,'24',45,7.0,18])
x

array(['12', '34', '24', '45', '7.0', '18'], dtype='<U11')

In [30]:
#data type
x.dtype

dtype('float64')

In [ ]:
#Type of the object
type(x)

In [31]:
#Type conversion
x.astype(int)

array([12, 34, 24, 45,  7, 18])

In [32]:
x.astype(str)

array(['12.0', '34.0', '24.0', '45.0', '7.0', '18.0'], dtype='<U32')

#### E. Some basic (1D) numpy operations

In [38]:
#Consider that we have two arrays

x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,55,1,10])

In [34]:
#Addition
x + y

array([15, 40, 32, 50,  8, 28])

In [35]:
y + 10

array([13, 16, 18, 15, 11, 20])

In [39]:
#Subtraction
x - y

array([  9,  28,  16, -10,   6,   8])

In [ ]:
#Multiplication by scalar
10*y

In [ ]:
y*(1/10)

In [ ]:
y/10

In [ ]:
#Element wise multiplication
x*y

In [37]:
#Using dot method
x.dot(y)

844

In [ ]:
np.sum(x*y)

In [ ]:
y.dot(x)

In [ ]:
np.dot(x,y)

In [ ]:
print(x)
print(y)

In [ ]:
#Taking the square root of each elements in an array
x**(1/2)

In [40]:
np.sqrt(x)

array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [41]:
np.exp(x)

array([1.62754791e+05, 5.83461743e+14, 2.64891221e+10, 3.49342711e+19,
       1.09663316e+03, 6.56599691e+07])

In [ ]:
np.log(x)

#### F. Some Useful Numpy Functions

In [ ]:
y = np.array([3,6,8,5,1,10])

In [ ]:
#Sum
np.sum(y)

In [ ]:
sum(y)

In [ ]:
#Mean
np.mean(y)

In [ ]:
#Standard Deviation
np.std(y)

In [ ]:
#Minimum
np.min(y)

In [ ]:
#Maximum
np.max(y)

In [42]:
#Percentiles
np.percentile(y,60)

8.0

In [43]:
np.percentile(y,[25, 62, 75])

array([3.75, 8.2 , 9.5 ])

In [44]:
#Sorting
np.sort(y)

array([ 1,  3,  6,  8, 10, 55])

In [46]:
#Sorting in descending order
-np.sort(-y)

array([55, 10,  8,  6,  3,  1])

#### G. Subsetting a 1D numpy array

In [47]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [48]:
#Subsetting and slicing is same as list
x[0]

12

In [49]:
x[1]

34

In [ ]:
y[3]

In [50]:
x[3:5]

array([45,  7])

In [51]:
x[[2,4]]

array([24,  7])

#### H. Conditional Subsetting

**The Comparison Operators**

      > is greater than
      < is less than
      == is equal to
      <= is less than or equal to
      >= is greater than or equal to

In [52]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [53]:
2 > 30

False

In [54]:
x > 20

array([False,  True,  True,  True, False, False])

In [55]:
y <= 5

array([ True, False, False,  True,  True, False])

In [56]:
sum(y <= 5)

3

In [ ]:
y == 1

**The Logical Operators**

    AND: &
    OR : |

In [57]:
(x>30) | (x<10)

array([False,  True, False,  True,  True, False])

In [ ]:
(x>10)

In [ ]:
(x<30)

In [ ]:
(x>10) | (x<30)

**Problems**

In [17]:
#Consider the following two vectors

x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

In [18]:
np.logical_not(x < 35)

array([False,  True, False,  True,  True,  True])

In [58]:
#a. Vaues of x that are less than 35

x[x < 35]

array([12, 34, 24,  7, 18])

In [19]:
#no. of obs of y more than 150
y[y > 150].size

2

In [20]:
#OR
sum(y > 150)

2

In [ ]:
#c. The number of observations in y that are between 120 and 165

sum((y >= 120) & (y <= 165))

In [ ]:
#d. The vaues in x that are less than 30 or greater than 50
x[((x < 30) | (x > 50))]

In [21]:
#e. The values in x for which the values in y is less than or equal to 120
x[y <= 120]

array([33, 67])

In [ ]:
#f. The values in y for which the values in x is equal to 45
y[x == 45]

#### I. Defining a 2D numpy array

In [59]:
#Converting a 1D array into 2D array
x = np.array([33,45,23,67,54,48])

matrix = x.reshape(2,3)
matrix

array([[33, 45, 23],
       [67, 54, 48]])

In [60]:
matrix = x.reshape(3,2)
matrix

array([[33, 45],
       [23, 67],
       [54, 48]])

In [23]:
#Create a 3x3 matrix containing elements from 1 to 9

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
#Joining two 1D arrays to form a matrix
x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

matrix = np.array([x,y])
matrix

array([[ 33,  45,  23,  67,  54,  48],
       [108, 151, 164, 119, 135, 122]])

#### J. Some basic methods for 2D numpy array

In [62]:
matrix = np.array([ [38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [63]:
matrix.shape

(5, 3)

In [64]:
matrix.ndim

2

In [65]:
matrix.dtype

dtype('int32')

In [66]:
matrix.dtype.name

'int32'

In [67]:
matrix.size

15

In [68]:
#Size of the matrix in bytes
matrix.itemsize

4

#### K. Subsetting 2D numpy array

In [27]:
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [ ]:
#a) Print the first element of the matrix.
matrix[0,0]


In [ ]:
#b) Print the last element of the matrix.
matrix[matrix.shape[0]-1, matrix.shape[1]-1]


In [25]:
matrix.shape

(2, 6)

In [26]:
#Or
matrix[-1,-1]

122

In [ ]:
matrix[0]

In [28]:
#c) Print the values of the first row.

matrix[0,:]


array([38, 33, 47])

In [ ]:
#d) Print the values of the fourth row.

matrix[3,:]


In [ ]:
#e) Print the values first column.

matrix[:,0]


In [ ]:
#f) Calculate the total of the third row.

np.sum(matrix[2,])


In [ ]:
matrix[2,]

In [ ]:
#g) Calculate the total of the fifth row.

np.sum(matrix[4,])


In [ ]:
#h) Calculate the total of the second column.

np.sum(matrix[:,1])


In [ ]:
#i) Calculate the average of the values of the first row.

np.mean(matrix[0,])


In [70]:
#j) Replace the first value of the matrix by 50.

matrix[0,0] = 50
matrix


array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [71]:
#k) Replace the last value of the matrix by 30.

matrix[-1, -1] = 30
matrix


array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 30]])

In [29]:
#l) Replace the second column of the matrix by the array (20,30,20,30,20)

matrix[:,1] = np.array([20,30,20,30,20])
matrix


array([[38, 20, 47],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 43]])

In [30]:
np.mean(matrix[0, ])

35.0

In [31]:
#m) Replace the first row of the matrix by its average (calculated above).

matrix[0,:] = np.mean(matrix[0,:])

In [32]:
matrix

array([[35, 35, 35],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 43]])

In [75]:
#q) Calculate the sum of all the elements of the matrix

np.sum(matrix)

466

In [33]:
#r) Calculate the sum of all the rows on the matrix

np.sum(matrix, axis=1)

array([105,  94,  88,  89,  91])

In [34]:
#s) Calculate the sum of all the colummns of the matrix

np.sum(matrix, axis=0)

array([151, 135, 181])

#### L. Matrix Operations

In [76]:
#Defining a matrix 'm'
m = np.array([[2,3],[4,5]])
m

array([[2, 3],
       [4, 5]])

In [77]:
#Defining a matrix 'n'
n = np.array([[1,0],[3,6]])
n

array([[1, 0],
       [3, 6]])

In [ ]:
#Multiplication by scalar
2*n

In [ ]:
#Matrix addition
m + n

In [78]:
#Matrix Multilication
np.dot(m,n)

array([[11, 18],
       [19, 30]])

In [79]:
#Preferred - for Matrix Multilication
np.matmul(m,n)

array([[11, 18],
       [19, 30]])

In [80]:
#Preferred - for Matrix Multilication
m @ n

array([[11, 18],
       [19, 30]])

In [81]:
#Element-wise array multilication
np.multiply(m,n)

array([[ 2,  0],
       [12, 30]])

In [82]:
m*n

array([[ 2,  0],
       [12, 30]])

#### Copying data

In [88]:
p = np.array([2,5,8,6])

In [84]:
q = p #note that not new object is created

In [85]:
q

array([2, 5, 8, 6])

In [86]:
q[2] = 10
q

array([ 2,  5, 10,  6])

In [87]:
p

array([ 2,  5, 10,  6])

In [89]:
q = p.copy()

In [90]:
q[2] = 100
q

array([  2,   5, 100,   6])

In [91]:
p

array([2, 5, 8, 6])