## Linear Regression - Closed Form Solution Vs Solution using Gradient Descent Algorithm

In [1]:
#Linear Regression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import os

In [3]:
#For linear Regression using the statsmodels package
import statsmodels.api as stm
import math
os.getcwd()

'C:\\Users\\hp\\Documents\\Praxis_Docs\\GOURAB_SIR_PYTHON_ML\\ML'

### Data: Cars.csv

In [5]:
#Setting the working directory
os.chdir(r"C:\\Users\\hp\\Documents\\Praxis_Docs\\GOURAB_SIR_PYTHON_ML\\ML")

#Reading the data
cars = pd.read_csv("cars.csv")
cars.head()

Car   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0          8         307.0         130   
1          Buick Skylark 320  15.0          8         350.0         165   
2         Plymouth Satellite  18.0          8         318.0         150   
3              AMC Rebel SST  16.0          8         304.0         150   
4                Ford Torino  17.0          8         302.0         140   

   Weight  Acceleration  Model Origin  
0    3504          12.0     70     US  
1    3693          11.5     70     US  
2    3436          11.0     70     US  
3    3433          12.0     70     US  
4    3449          10.5     70     US

In [6]:
#Let us remove the observations for which MPG is 0
cars2 = cars.loc[(cars.MPG != 0) & (cars.Horsepower != 0), ]

In [7]:
print(cars.shape)
print(cars2.shape)

(406, 9)
(392, 9)


In [8]:
X = cars2[['Weight',"Acceleration","Horsepower"]]
X = stm.add_constant(X)
y = cars2.MPG

C:\Users\hp\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


In [9]:
X.head()

const  Weight  Acceleration  Horsepower
0    1.0    3504          12.0         130
1    1.0    3693          11.5         165
2    1.0    3436          11.0         150
3    1.0    3433          12.0         150
4    1.0    3449          10.5         140

### Linear Regression - Statsmodels Solution

In [10]:
model = stm.OLS(y,X).fit()
model.params

const           45.678293
Weight          -0.005789
Acceleration    -0.002066
Horsepower      -0.047496
dtype: float64

### Linear Regression - Closed Form Solution (Using Matrix)

In [12]:
#Converting the Data Frames into matrix
X = np.array(X)
y = np.array(y)

In [13]:
#Transpose of X
tX = np.transpose(X)

In [14]:
#Closed form solution for the coefficients
np.matmul(np.matmul(np.linalg.inv(np.matmul(tX,X)), tX),y)

array([ 4.56782929e+01, -5.78940259e-03, -2.06565785e-03, -4.74956153e-02])

### Non-Invertibility of a Matrix

In [15]:
h = np.array([[1,3,5],
             [2,9,9],
             [2.5,7.5,12.5]])    

h = np.transpose(h) #Note: Col3 = 2.5*Col1

In [16]:
h

array([[ 1. ,  2. ,  2.5],
       [ 3. ,  9. ,  7.5],
       [ 5. ,  9. , 12.5]])

In [17]:
#Inverse of the matrix
np.linalg.inv(h)

array([[ 3.24259173e+16, -1.80143985e+15, -5.40431955e+15],
       [-4.00000000e+00,  5.00000000e-01,  5.00000000e-01],
       [-1.29703669e+16,  7.20575940e+14,  2.16172782e+15]])

In [ ]:
np.linalg.det(h)

In [ ]:
#Deterninant of the product of tX and X
np.linalg.det(np.matmul(np.transpose(h),h))

In [ ]:
np.linalg.inv(np.matmul(np.transpose(h),h))

**Note** This is a problem that can be caused due to the presence of multicollinearity...

### Simple Linear Regression - with Gradient Descent

In [21]:
import pandas as pd
mtcars = pd.read_csv("mtcars.csv")

In [22]:
mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [24]:
#X and y
X = mtcars[['wt']]
X = stm.add_constant(X)
y = mtcars['mpg']

X = np.array(X)
y = np.array(y)

In [25]:
print(X.shape)
print(y.shape)

(32, 2)
(32,)


In [26]:
y=y.reshape(32,1)

In [33]:
#Initialize the weight vector
beta = np.array([[0],[0]])

#Fix a atep size
eta = 0.0025

#Optimization

for i in range(1,1000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,beta)))
    #if i > 500:
    #    print(delta)
    beta = beta - (-2)*eta*delta


beta

array([[37.28494997],
       [-5.34442097]])

#### Cross-Checks

In [34]:
model = stm.OLS(y,X).fit()

In [35]:
model.params

array([37.28512617, -5.34447157])

### One Challenge - Gradient Descent may go Crazzy without Feature Scaling!

In [36]:
#X and y
X = cars[['Weight']]
X = stm.add_constant(X)
y = cars['MPG']

X = X.as_matrix()
y = y.as_matrix()

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [ ]:
y.shape

In [37]:
y=y.reshape(406,1)

In [38]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a step size
alpha = 0.000000001


#Optimization
for i in range(1,100000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    #print(delta)
    weight = weight - (-2)*alpha*delta


weight

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in matmul
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in matmul
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in subtract
  del sys.path[0]


array([[nan],
       [nan]])

### Muliple Linear Regression - Gradient Descent with Feature Scaling

In [ ]:
cars_scaled = cars[['MPG','Weight','Horsepower']].apply(lambda x: (x - np.min(x)) / (np.max(x) - np.min(x)))

In [ ]:
cars_scaled.head()

In [ ]:
#X and y
X = cars_scaled[['Weight']]
X = stm.add_constant(X)
y = cars_scaled['MPG']

X = X.as_matrix()
y = y.as_matrix()
y=y.reshape(406,1)

In [ ]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a atep size
alpha = 0.001


#Optimization
for i in range(1,80000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    #print(delta)
    weight = weight - (-2)*alpha*delta


weight

In [ ]:
model = stm.OLS(y,X).fit()
model.params

### GRADIENT DESCENT FUNCTION WITH SCALED (STANDARDISED) FEATURES

In [39]:
cars_scaled2 = cars[['MPG','Weight','Horsepower']].apply(lambda x: (x - np.mean(x)) / np.std(x))

In [40]:
cars_scaled2.mean()

MPG          -8.485276e-16
Weight       -6.699622e-18
Horsepower    3.809213e-16
dtype: float64

In [41]:
cars_scaled2.std()

MPG           1.001234
Weight        1.001234
Horsepower    1.001234
dtype: float64

In [ ]:
#X and y
X = cars_scaled2[['Weight']]
X = stm.add_constant(X)
y = cars_scaled2['MPG']

X = X.as_matrix()
y = y.as_matrix()
y=y.reshape(406,1)

In [43]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a atep size
alpha = 0.001


#Optimization
for i in range(1,1000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    weight = weight - (-2)*alpha*delta


weight

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in matmul
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in matmul
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in subtract
  if sys.path[0] == '':


array([[nan],
       [nan]])

In [ ]:
model = stm.OLS(y,X).fit()
model.params

### GRADIENT DESCENT FUNCTION WITH SCALED (STANDARDISED) FEATURES [USING WHILE LOOP]

In [44]:
cars_scaled2 = cars[['MPG','Weight','Horsepower']].apply(lambda x: (x - np.mean(x)) / np.std(x))

In [45]:
#X and y
X = cars_scaled2[['Weight']]
X = stm.add_constant(X)
y = cars_scaled2['MPG']

X = X.as_matrix()
y = y.as_matrix()
y=y.reshape(406,1)

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [47]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a atep size
alpha = 0.001
delta = 1
tolerance = 10e-10
count = 0

#Optimization
while np.sqrt(np.sum(delta**2)) > tolerance:
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    weight = weight - (-2)*alpha*delta
    count += 1


print(count)
print(weight)

17
[[-7.96696042e-16]
 [-7.87509941e-01]]


### PREDICTION USING THE COEFFICIENTS

In [48]:
#Getting the fitted values
pred = np.matmul(X,weight)
pred[:10]

array([[-0.48834055],
       [-0.66428182],
       [-0.42503893],
       [-0.42224621],
       [-0.43714071],
       [-1.26750903],
       [-1.27961081],
       [-1.24051275],
       [-1.34570515],
       [-0.81043409]])

Note that given a new  data we need to scale the data and add a constant column then use it to make prediction in the same way as above